"""Configurações centrais do projeto de RH com IA."""

COMPANY_CULTURE = {
    "nome": "TechNova Solutions",
    "missao": "Transformar negócios através de tecnologia inovadora e pessoas extraordinárias",
    "valores": [
        "Inovação contínua",
        "Colaboração e trabalho em equipe",
        "Transparência e comunicação aberta",
        "Diversidade e inclusão",
        "Equilíbrio entre vida pessoal e profissional",
        "Aprendizado constante",
        "Orientação a resultados com ética",
    ],
    "ambiente": "Híbrido (3 dias presencial, 2 remoto)",
    "estilo_lideranca": "Liderança servidora e participativa",
    "tom_comunicacao": "Informal mas profissional",
    "perfil_ideal": {
        "adaptabilidade": "Alta - ambiente de mudanças constantes",
        "autonomia": "Alta - confiança nos profissionais",
        "colaboracao": "Essencial - squads multidisciplinares",
        "inovacao": "Incentivada - hackathons trimestrais",
        "crescimento": "Plano de carreira estruturado com mentorias",
    },
    "beneficios": [
        "PLR semestral",
        "Plano de saúde e dental",
        "Gympass",
        "Auxílio home office",
        "Budget de educação anual",
        "Day off no aniversário",
        "Stock options para Sênior+",
    ],
}

AVAILABLE_POSITIONS = {
    "engenheiro_software": {
        "titulo": "Engenheiro(a) de Software Pleno",
        "departamento": "Technology",
        "nivel": "Pleno",
        "habilidades_tecnicas": ["Python", "JavaScript/TypeScript", "SQL", "Git", "APIs REST", "Docker", "CI/CD", "Testes automatizados"],
        "habilidades_comportamentais": ["Resolução de problemas", "Comunicação", "Trabalho em equipe", "Proatividade", "Pensamento analítico"],
        "experiencia_minima_anos": 3,
        "faixa_salarial": "R$ 8.000 - R$ 14.000",
        "descricao": "Desenvolvedor(a) responsável por construir e manter sistemas de alta disponibilidade em squads ágeis.",
    },
    "analista_dados": {
        "titulo": "Analista de Dados Sênior",
        "departamento": "Research & Development",
        "nivel": "Sênior",
        "habilidades_tecnicas": ["Python", "SQL", "Power BI/Tableau", "Estatística", "Machine Learning", "ETL", "Big Data"],
        "habilidades_comportamentais": ["Pensamento analítico", "Storytelling com dados", "Visão de negócio", "Atenção a detalhes"],
        "experiencia_minima_anos": 5,
        "faixa_salarial": "R$ 10.000 - R$ 18.000",
        "descricao": "Profissional que transforma dados brutos em insights estratégicos para decisões de negócio.",
    },
    "gerente_projetos": {
        "titulo": "Gerente de Projetos",
        "departamento": "Sales",
        "nivel": "Sênior",
        "habilidades_tecnicas": ["Metodologias ágeis (Scrum/Kanban)", "Jira/Asana", "Gestão de riscos", "OKRs", "Budget management"],
        "habilidades_comportamentais": ["Liderança", "Comunicação", "Negociação", "Gestão de conflitos", "Visão estratégica"],
        "experiencia_minima_anos": 5,
        "faixa_salarial": "R$ 12.000 - R$ 20.000",
        "descricao": "Líder responsável por coordenar projetos estratégicos, garantindo entregas no prazo e dentro do orçamento.",
    },
    "analista_rh": {
        "titulo": "Analista de RH",
        "departamento": "Human Resources",
        "nivel": "Pleno",
        "habilidades_tecnicas": ["Recrutamento e seleção", "Treinamento e desenvolvimento", "Legislação trabalhista", "People Analytics", "Excel avançado"],
        "habilidades_comportamentais": ["Empatia", "Comunicação", "Organização", "Sigilo profissional", "Mediação de conflitos"],
        "experiencia_minima_anos": 3,
        "faixa_salarial": "R$ 5.000 - R$ 9.000",
        "descricao": "Profissional que cuida de todo o ciclo de vida do colaborador, desde a atração até o desenvolvimento.",
    },
    "designer_ux": {
        "titulo": "Designer UX/UI",
        "departamento": "Research & Development",
        "nivel": "Pleno",
        "habilidades_tecnicas": ["Figma", "Design System", "Pesquisa com usuário", "Prototipação", "HTML/CSS básico", "Acessibilidade"],
        "habilidades_comportamentais": ["Criatividade", "Empatia com usuário", "Comunicação visual", "Colaboração", "Pensamento crítico"],
        "experiencia_minima_anos": 3,
        "faixa_salarial": "R$ 7.000 - R$ 13.000",
        "descricao": "Designer responsável por criar experiências digitais intuitivas e acessíveis para produtos TechNova.",
    },
    "engenheiro_ml": {
        "titulo": "Engenheiro(a) de Machine Learning",
        "departamento": "Research & Development",
        "nivel": "Sênior",
        "habilidades_tecnicas": ["Python", "TensorFlow/PyTorch", "Scikit-learn", "MLOps", "Feature Engineering", "Docker/Kubernetes", "SQL/NoSQL", "Cloud (AWS/GCP)"],
        "habilidades_comportamentais": ["Pensamento científico", "Comunicação técnica", "Autonomia", "Resolução de problemas complexos", "Colaboração cross-funcional"],
        "experiencia_minima_anos": 4,
        "faixa_salarial": "R$ 15.000 - R$ 25.000",
        "descricao": "Responsável por desenvolver, treinar e colocar em produção modelos de ML para produtos e processos da TechNova.",
    },
    "product_manager": {
        "titulo": "Product Manager",
        "departamento": "Technology",
        "nivel": "Sênior",
        "habilidades_tecnicas": ["Product Discovery", "Roadmap", "OKRs", "A/B Testing", "Analytics (Mixpanel/Amplitude)", "SQL básico", "Prototipação"],
        "habilidades_comportamentais": ["Visão de produto", "Liderança sem autoridade", "Comunicação", "Priorização", "Orientação a dados", "Empatia com cliente"],
        "experiencia_minima_anos": 4,
        "faixa_salarial": "R$ 12.000 - R$ 22.000",
        "descricao": "PM responsável por definir estratégia, roadmap e prioridades de um produto digital de alto impacto.",
    },
}

FEATURE_MAPPING = {
    "compatibilidade_vaga": {"descricao": "Probabilidade de fit técnico com a vaga", "threshold_aprovacao": 0.7},
    "compatibilidade_cultura": {"descricao": "Alinhamento com os valores e cultura da empresa", "threshold_aprovacao": 0.65},
    "risco_attrition": {"descricao": "Probabilidade de o candidato pedir demissão em até 2 anos", "threshold_alerta": 0.4},
    "potencial_crescimento": {"descricao": "Potencial de crescimento e desenvolvimento na empresa", "threshold_destaque": 0.75},
}

POSITION_WEIGHTS = {
    "engenheiro_software": {"technical_skills": 0.40, "communication": 0.15, "teamwork": 0.15, "soft_skills": 0.10, "growth_potential": 0.20},
    "analista_dados":      {"technical_skills": 0.45, "communication": 0.20, "teamwork": 0.10, "soft_skills": 0.10, "growth_potential": 0.15},
    "gerente_projetos":    {"technical_skills": 0.20, "communication": 0.25, "teamwork": 0.20, "soft_skills": 0.20, "growth_potential": 0.15},
    "analista_rh":         {"technical_skills": 0.20, "communication": 0.25, "teamwork": 0.25, "soft_skills": 0.20, "growth_potential": 0.10},
    "designer_ux":         {"technical_skills": 0.30, "communication": 0.20, "teamwork": 0.20, "soft_skills": 0.15, "growth_potential": 0.15},
    "engenheiro_ml":       {"technical_skills": 0.50, "communication": 0.10, "teamwork": 0.10, "soft_skills": 0.10, "growth_potential": 0.20},
    "product_manager":     {"technical_skills": 0.15, "communication": 0.30, "teamwork": 0.20, "soft_skills": 0.20, "growth_potential": 0.15},
}
